{% set version = "5.4.1" %}
{% set variant = "openblas" %}

package:
  name: gmt
  version: {{ version }}

source:
  fn: gmt-{{ version }}-src.tar.gz
  url: ftp://ftp.soest.hawaii.edu/gmt/gmt-{{ version }}-src.tar.gz
  sha256: c85541d50b63a5f0809552edb488bb69995b96dd684df77d6328a9eea7ff3ab0

build:
  number: 1
  skip: True  # [win or osx]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - cmake
    - fftw
    - gdal 2.2.*
    - ghostscript
    - libnetcdf 4.4.*
    - hdf5 1.8.17|1.8.17.*
    - zlib 1.2.*
    - blas 1.1 {{ variant }}
    - curl
  run:
    - fftw
    - gdal 2.2.*
    - ghostscript
    - libnetcdf 4.4.*
    - hdf5 1.8.17|1.8.17.*
    - zlib 1.2.*
    - blas 1.1 {{ variant }}
    - curl

test:
  commands:
    - gmt psbasemap -R10/70/-3/8 -JX4i/3i -Ba -B+glightred+t"TEST" -P > test0.ps  # [not win]
    - gmt pscoast -Vd -R0/5/0/5 -JM5i -P -W0.25p > test1.ps  # [not win]
    - gmt pscoast -R-130/-70/24/52 -JB-100/35/33/45/6i -Ba -B+t"Conic Projection" -N1/thickest -N2/thinnest -A500 -Ggray -Wthinnest -P > test2.ps
    - conda inspect linkages -p $PREFIX gmt  # [not win]
    - conda inspect objects -p $PREFIX gmt  # [osx]

about:
  home: http://gmt.soest.hawaii.edu/
  license: LGPL-3.0
  license_file: LICENSE.TXT
  summary: 'Generic Mapping Tools.'

extra:
  recipe-maintainers:
    - ocefpaf
    - leouieda
