travis:
  secure:
    BINSTAR_TOKEN: ciuYQlwMqZ9sd0kI8lEo6ehEAqcCHaFTJnNmxBojb+2caA7lGsrm2bdyls/G1B/TmwAuXsVTbGlXIE432VSz1xhuEQ/rrU2CqT3wCyP3PBc8b59UIgEWChauS4KB1EH8xdbTTCqAqGYEirmcpGgZJ00cGSy8FoZqDxd13CiRp1yAtypZkykWcrCyvSs41raSfj9hRnJg06DqA/DaadLB0kF0cwSAl8ciQGXQ+gzVLk6pn50X7BLt9Pkzg7cAA5I9TwTJskzT5d16skUJTKtC26D4wV1dyyNWxSn5H1DFSSpEV6ioAs8+K+EBdKpaomFOg2tculIRB5Bt7oJxlomTcBfqiX2rT2wOND/EQaYa6DyNA7lqVCVaH1I4m0wXwfsFi52QdVydNLDX90Ro40DOy6ggl1Db+8319aSxgxkXNRCp8XppJKsMeuHhj3SbymF0l21bD+7+Nk6UFCki00ZUNpiGFRshoDnEwPZO3eNvSRuB6Ko8cg5StPc5fpDXXMrshWfNg5qSUvjn01dk9B3dxKwD3kLIRHnYTypvH1RHj7BjuTU5cJfVuYyKudtf84wcYM/Rc7Ssy7hEp1wQ7l4LXw+4Hzhio86G5Goq6Q6fieOZ5+Zn2Vkw+6luYKcYStrRt/zrBnkqtq4dSYr4DxLMCbr5nfYXQIBz9q0bxOc3o+0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
channels:
  targets:
    - [conda-forge, dev]
