travis:
  secure:
    BINSTAR_TOKEN: Gaegn98c9/ZoMtQ+r6sZv2ML7wPv988rjKhrgnhR98kXaEdZkh+hSUEAcFpBJDUdzRlSLhnW3y2FcTM9013KST03tnueHECqsrWWDoy+APTY0znvL08IFY85JxiEBQGigTDvzzvd2PqE6JF09ecf7aP10Y2XVLuTvH+HfDQO3G7GiJ4TxQP4ZJcb43wpEbHiDreIuNOTFajNRsr3T35/8ikay8VsGi2YHgYNJtlEkCTCJip6fDFfrOpYDEvBaVXsLXd5x24Xn8KRlORLx6c020PNkGDTfUhddMd+zkjKd/2mdj2gAJKcfBWhsGqPVF6QH9orzb0V7wQW6rMOhkAVInxhnDvuY2uzDdv9nWRGs+dZOXAousDiKhiy9HXBMwQGXyjGH/BQ9+Wbyfg6/Jds9fw+vMqh+eLrmfMfO1neFxhGWTmoJ/ChqjiZw2Osk0r/RtafOvV//daPZ73/slCQTqy26oSTpWpZnKwzFuO+x5dcqhsOqrNS5Kacwb323+jc01z17JmbuBRuSAqyn3qzdfpeBxmGRaEJ8tIOVij2DteVJvzZyd9CbokLCmlXYWqZ5zxREnbjiEDD9EqkQO78DN+CQyxdioDz1xREKuE68TjWf57GT2LAQ00x4eWFIbSF4Y2s6fofyxcJOWdeBjFs+JwjzzwwwoDWB2L07wsxs7Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
channels:
  targets:
    - [conda-forge, dev]
