on:
  pull_request:
    branches:
      - devel
  # Schedule runs on 9am every Sunday
  schedule:
    - cron: '0 9 * * 0'

jobs:
  bump-dev-version:
    name: Bump GMT development version
    runs-on: ubuntu-latest

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v2.3.1

      # Get latest GMT sha hash from Github
      - name: Get git revision number
        id: git_rev_info
        run: echo ::set-output name=sha::$(git ls-remote https://github.com/GenericMappingTools/gmt HEAD | cut -f 1)

      # Change Github sha hash
      - name: Update git revision number
        uses: mikefarah/yq@3.3.2
        with:
          cmd: "yq write --inplace recipe/meta.yaml 'source.git_rev' ${{ steps.git_rev_info.outputs.sha }}"

      # Bump build version number
      - name: Bump build number
        uses: mikefarah/yq@3.3.2
        with:
          cmd: "yq write --inplace recipe/meta.yaml 'build.number' 1"

      # Take a look at recipe/meta.yaml contents
      - name: Check meta.yaml contents
        run: cat recipe/meta.yaml

      # TODO Commit changed recipe/meta.yaml file to Github
      # - name: Commit changes
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Bump GMT dev version
      #     branch: devel
