on:
  pull_request:
    branches:
      - devel
  # Schedule runs on 9am every Sunday
  schedule:
    - cron: '0 9 * * 0'

jobs:
  bump-dev-version:
    name: Bump GMT development version
    runs-on: ubuntu-latest
    if: github.repository != 'conda-forge/gmt-feedstock'

    steps:
      # Checkout current git repository
      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          repository: conda-forge/gmt-feedstock
          ref: devel

      # Install yq - A portable command-line YAML processor
      - name: Install yq
        run: |
          sudo wget -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.3.4/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      # Get the GMT package's latest hash from Github
      # and build the desired conda version string. For example:
      # SHA_HASH=abcdefghijklmnopqrstuvwxyz12345678901234, VERSION_STRING=1.2.3.dev1+hijklmn
      - name: Get package's latest git revision and build version string
        id: version_info
        run: |
          ## Get the sha hash value (e.g. abcdefghijklmnopqrstuvwxyz12345678901234) from Github
          export SHA_HASH=$(git ls-remote https://github.com/GenericMappingTools/gmt HEAD | cut -f 1)
          echo ::set-output name=SHA_HASH::$SHA_HASH

          ## Build new version string (e.g. 1.2.3.dev1+hijklmn)

          # Get tag with highest version number (e.g. 1.2.3)
          export TAG=$(git ls-remote -q --sort="-version:refname" --tags --refs https://github.com/GenericMappingTools/gmt | head -n 1 | cut -d / -f 3)

          # Add 1 to the previous dev version number (e.g. 1.2.3.dev0+abcdefg would output 1)
          export DEV_VERSION_NUM=`expr 1 + $(yq read recipe/meta.yaml package.version | grep -o -P '(?<=dev).*(?=\+)')`

          # Get short sha hash value (e.g. hijklmn)
          export SHORT_HASH=$(echo $SHA_HASH | cut -c 1-7)

          # Finally build the new version string (e.g. 1.2.3.dev1+hijklmn)
          echo ::set-output name=VERSION_STRING::$TAG.dev$DEV_VERSION_NUM+$SHORT_HASH

      # Change development package version and source git revision
      - name: Update package version and git revision
        run: |
          # Update the recipe/meta.yaml file with new version info
          yq write --inplace recipe/meta.yaml package.version ${{ steps.version_info.outputs.VERSION_STRING }}
          yq write --inplace recipe/meta.yaml source.git_rev ${{ steps.version_info.outputs.SHA_HASH }}

          # Fix incorrectly formatted {{ compiler('c') }}
          yq write --inplace recipe/meta.yaml requirements.build[1] "{{ compiler('c') }}"
          sed --in-place "s/'{{ compiler(''c'') }}'/{{ compiler('c') }}/g" recipe/meta.yaml

          # Ensure <two spaces>#<one space>[<expression>] form
          sed --in-place "s/\ \#\ \[/  # [/g" recipe/meta.yaml

      # Take a look at recipe/meta.yaml contents
      - name: Check meta.yaml contents
        run: cat recipe/meta.yaml

      # Open a Pull Request from personal fork to the upstream repo
      # The GMT_FEEDSTOCK_TOKEN personal access token secret should have
      # a scope of "repo: public_repo" for access to public repositories
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.4.0
        with:
          title: "Bump GMT dev version to ${{ steps.version_info.outputs.VERSION_STRING }}"
          commit-message: "Bump GMT dev version to ${{ steps.version_info.outputs.VERSION_STRING }}"
          reviewers: "weiji14"  # TODO change to someone else
          base: devel
          branch: update/${{ steps.version_info.outputs.VERSION_STRING }}
          delete-branch: true
          token: ${{ secrets.GMT_FEEDSTOCK_TOKEN }}
          draft: true
          push-to-fork: GenericMappingTools/gmt-feedstock
          body: |
            It is very likely that the current package version for this feedstock is out of date.

            This PR will update the following package:
                - gmt=`${{ steps.version_info.outputs.VERSION_STRING }}`

            Notes for merging this PR:
              1. Feel free to push to the bot's branch to update this PR if needed.
              2. Checklist before merging this PR:
              - [ ] Dependencies have been updated if changed
              - [ ] Tests have passed
